services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eventsdb
    restart: always

  app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HMAC_SECRET: mysecret
      MONGODB_URI: mongodb://mongo:27017/eventsdb
      ROUTING_SERVICE_URL: http://localhost:3000/stub/route
      NODE_ENV: development
    depends_on:
      - redis
      - mongo
    restart: always